### ISSUE TITLE
Event page

### ISSUE THREAD

**Issue by riccardoSocialcities** [edgecowork/website-onepager#18]
### Newsletter events
- [x] Suscribete para saber sobre nuestros proximo eventos
- [x] List in mailchimp

### List events
- [x] Page with the past events
- [x] Figure out if and how put the Location
- [x] Rich snippet for events

### Todo in the page
- [x] Ajax functions for sending the email
- [x] Graphic handler for the form

**Comment by riccardoSocialcities** [comment]
@diegomorales85 do you already have the mailing list for the events?
